/hospital_carrier:
   ReadAruco:
      ros__parameters:
         camera_shape:
            rows: 2
            cols: 1
            dt: d
            data: [ 640., 480. ]
         camera_matrix:
            rows: 3
            cols: 3
            dt: d
            data: [ 612.1918334960938, 0.0, 327.3767395019531, 0.0, 611.064453125, 240.07266235351562, 0.0, 0.0, 1.0 ]
         distortion_coefficients :
            rows: 1
            cols: 5
            dt: d
            data: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
